celeryd:
  BROKER_URL: redis://localhost:6379/0
  CELERYD_TASK_TIME_LIMIT: 60
  CELERY_IMPORTS: [handlers.tasks]
  CELERY_ENABLE_UTC: true
  CELERY_ACCEPT_CONTENT: [json]
  CELERY_TASK_SERIALIZER: json
  CELERY_RESULT_SERIALIZER: json
  CELERY_BACKEND: redis

celerybeat:
  BROKER_URL: redis://localhost:6379/0
  CELERY_TIMEZONE: UTC
  CELERY_ENABLE_UTC: true
  CELERY_DISABLE_RATE_LIMITS: True
  CELERY_ACCEPT_CONTENT: [json]
  CELERY_TASK_SERIALIZER: json
  CELERY_RESULT_SERIALIZER: json
  CELERYBEAT_SCHEDULE:
    conditions_to_db:
      task: 'handlers.tasks.insert_all_conditions'
      schedule:
        crontab:
          minute: '*/10'
    light_watchdog:
      task: 'handlers.tasks.light_watchdog'
      schedule:
        crontab:
          minute: '*/1'
    fan_watchdog:
      task: 'handlers.tasks.fan_watchdog'
      schedule:
        crontab:
          minute: '*/1'
    soilmoisture_a_watchdog:
      task: 'handlers.tasks.soilmoisture_a_watchdog'
      schedule:
        crontab:
          minute: '*/1'
#    soilmoisture_b_watchdog:
#      task: 'handlers.tasks.soilmoisture_b_watchdog'
#      schedule:
#        crontab:
#          minute: '*/1'
#    shoot_frame:
#      task: 'handlers.tasks.shoot_frame'
#      schedule:
#        crontab:
#          minute: '*/20'
#      options:
#        queue: 'main'

sensors:
  gpio_pins:
    soil_moisture_1: 5
    soil_moisture_2: 6
    soil_moisture_3: 13
    soil_moisture_4: 16
    DHT22: 18
  ids:
    ds18b20_a: 28-0000076aa408
    ds18b20_b: 28-0000076bb328

relays:
  gpio_pins:
    servo: 17
    lights: 19
    pump_a: 20
    pump_b: 21
    fans: 26

mongodb:
  port: 27017
  db_name: 'greenhouse'

mqtt_topics_sub:
  lights: 'light/'
  fans: 'fan/'
  pumps: 'pump/'
  servo: 'window/'

mqtt_topics_pub:
  'lights': 'light/status'
  'fans': 'fan/status'
  'pumps': 'pump/status'
  'servo': 'window/status'

cloud_mqtt_cred:
  user: 'bwyhxlso'
  pass: 'Wna3huueUhrJ'
  server: 'm21.cloudmqtt.com'
